<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Simulation.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NovolisStackAnalyzers>false</NovolisStackAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.Math.Arrays" />
    <PackageReference Include="Novolis.Math.Geometry" />
    <PackageReference Include="Novolis.Physics.Abstractions" />
    <PackageReference Include="Novolis.Physics.Collision.Simple" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Novolis.Simulation.Racing/Novolis.Simulation.Racing.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Mesh/Novolis.Simulation.Mesh.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.View/Novolis.Simulation.View.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.World.Builders/Novolis.Simulation.World.Builders.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.World/Novolis.Simulation.World.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Replay/Novolis.Simulation.Replay.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Kinematics/Novolis.Simulation.Kinematics.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Abstractions/Novolis.Simulation.Abstractions.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Tiles/Novolis.Simulation.Tiles.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Voxels/Novolis.Simulation.Voxels.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Voxels.Meshing/Novolis.Simulation.Voxels.Meshing.csproj" />
    <ProjectReference Include="../../src/Novolis.Simulation.Humanoid/Novolis.Simulation.Humanoid.csproj" />
  </ItemGroup>
</Project>
